bikes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="pagina-inicial"),
    path("cadastrar/", views.cadastrar, name="cadastra-bike"),
    path("deletar_bike/<int:pk>/", views.deletar_bike, name="deleta-bike"),
    path("bikes/", views.ListarBikesListView.as_view(), name="listar-bikes"),
    path("bikes/update/<int:pk>/", views.UpdateBikeView.as_view(), name='atualiza-bike'),
    path("lojas/", views.ListarLojasView.as_view(), name="listar-lojas"),
    path("lojas/cadastrar", views.CadastrarLojaView.as_view(), name="cadastra-loja"),
    path("lojas/detalhes/<int:pk>/", views.DetalheLojaView.as_view(), name="detalha-loja"),
    path('lojas/atualizar/<int:pk>/',views.AtualizarLojaView.as_view(), name='atualizar-loja'),
    path('lojas/deletar/<int:pk>/', views.DeletarLojaView.as_view(), name='deletar-loja'),
    path("vendedores/", views.listar_vendedores, name="lista-vendedores"),
    path("vendedores/cadastrar/", views.cadastrar_vendedor, name="cadastra-vendedor"),
    path("venderores/atualizar/<int:pk>/", views.atualizar_vendedor, name='atualiza-vendedor'),
    path("contato/", views.contact_view, name="contato"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

# DUAS NOVAS IMPORTAÇÕES
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bikes.urls')),
    path('registration/', include('registration.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bikes/models.py
from django.db import models

# Create your models here.
class Bike(models.Model):
    modelo = models.CharField(max_length=30, verbose_name="Modelo da Bike")
    preco = models.FloatField(verbose_name='Preço')
    descricao = models.TextField(verbose_name='Descrição', blank=True, null=True)
    foto = models.ImageField(upload_to='bikes/', blank=True, null=True)

    def __str__(self):
        return self.modelo


class Loja(models.Model):
    nome = models.CharField(max_length=30, verbose_name='Nome')
    produtos = models.ManyToManyField(Bike)
    cnpj = models.CharField(max_length=25)
    detalhes = models.TextField()

    def __str__(self):
        return self.nome

class Vendedor(models.Model):
    nome = models.CharField(max_length=30, verbose_name="Nome")
    loja = models.ForeignKey(Loja, on_delete=models.CASCADE, verbose_name="Loja", related_name='vendedores')
    cpf = models.CharField(max_length=30)
    salario = models.FloatField(blank=True, null=True)
    
    def __str__(self):
        return self.nome

class BikeInventario(models.Model):
    numero_de_bikes = models.IntegerField()
    valor_total_de_bikes = models.FloatField()
    data_do_inventario = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-data_do_inventario"]

    def __str__(self):
        return f'Nº de Bikes {self.numero_de_bikes} | Valor total R$ {self.valor_total_de_bikes}'
    

bikes/forms.py
from django import forms
from django.forms import formset_factory
from .models import Bike, Loja, Vendedor


class BikeModelForm(forms.ModelForm):

    class Meta:
        model = Bike
        fields = "__all__"

    def clean_preco(self):
        preco_cadastro = self.cleaned_data['preco']

        if preco_cadastro < 200:
            self.add_error('preco', 'O preço não pode ser menor do que R$200')

        return preco_cadastro

    def clean_foto(self):
        tamanho_maximo = 2

        imagem = self.cleaned_data.get('foto')

        # Converter a imagem
        tamanho_imagem = tamanho_maximo * 1024 * 1024

        # Validando o tamanho da imagem
        if imagem.size > tamanho_imagem:
            raise forms.ValidationError('A imagem tem um tamanho maior que o suportado')
        return imagem


class LojaModelForm(forms.ModelForm):
    class Meta:
        model = Loja
        fields = '__all__'


class VendedorModelForm(forms.ModelForm):
    class Meta:
        model = Vendedor
        fields = '__all__'







# Exemplo de uso de formulário personalizado
class ContactForm(forms.Form):
    template_name = "form_snippet.html"
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

# Usando multiplos formulário de uma unica vez
ContactFormSet = formset_factory(ContactForm, extra=2)

# class BikeForm(forms.Form):
#     modelo = forms.CharField(max_length=30)
#     preco = forms.FloatField(label='Preço')
#     descricao = forms.CharField(label='Descrição', widget=forms.Textarea)
#     foto = forms.ImageField()


#     def save(self):
#         bike = Bike(
#            modelo = self.cleaned_data['modelo'],
#            preco = self.cleaned_data['preco'],
#            descricao = self.cleaned_data['descricao'],
#            foto = self.cleaned_data['foto']
#         )

#         bike.save()

#         return bike

bikes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DeleteView, DetailView, CreateView, TemplateView, UpdateView
from .forms import BikeModelForm,LojaModelForm, VendedorModelForm , ContactForm, ContactFormSet
from .models import Bike, Loja, Vendedor


# Views baseadas em funções
@login_required
def cadastrar_loja(request):

    if request.method == "POST":
        loja_form = LojaModelForm(request.POST)

        if loja_form.is_valid():
            loja_form.save()

            return redirect("listar-bikes")

    loja_form = LojaModelForm()
    return render(request, "formulario_loja.html", {"form": loja_form})


@method_decorator(login_required, name="dispatch")
class CadastrarLojaView(CreateView):
    model = Loja
    template_name = "formulario_loja.html"
    form_class = LojaModelForm
    success_url = "/lojas/"


# Views baseadas em classes
class HomeView(TemplateView):
    template_name = 'home.html'


class ListarLojasView(ListView):
    model = Loja
    template_name = "lojas.html"
    context_object_name = "lojas"


class ListarBikesView(View):

    def get(self, request):
        bikes = Bike.objects.all()
        return render(request, "produtos.html", {"bikes": bikes})

    def post(): ...


class ListarBikesListView(ListView):
    model = Bike
    template_name = "produtos.html"
    context_object_name = "bikes"  # Interessante sempre informar o nome do contexto
    paginate_by = 10
    

    def get_queryset(self):
        return Bike.objects.order_by('preco')
    


class AtualizarLojaView(UpdateView):
    model = Loja
    template_name = "formulario_loja_update.html"
    form_class = LojaModelForm
    success_url = "/lojas/"


class DeletarLojaView(DeleteView):
    model = Loja
    template_name = "detalhe_loja.html"
    success_url = "/lojas/"


class DetalheLojaView(DetailView):
    model = Loja
    template_name = "detalhe_loja.html"
    # context_object_name = 'loja_de_bike'

class UpdateBikeView(UpdateView):
    model = Bike
    template_name = 'formulario_bike_update.html'
    form_class = BikeModelForm
    success_url = "/bikes/"

def cadastrar(request):
    user = request.user
    if user.is_authenticated:
        if request.method == 'POST':
            bike_form = BikeModelForm(request.POST, request.FILES)
            if bike_form.is_valid(): 
                bike_form.save()
                return redirect("listar-bikes")
        else:
            bike_form = BikeModelForm()
        return render(request, 'formulario_bike.html', {'form': bike_form})
    else:
        return redirect("acessar")


# criar view para deletar aqui
def deletar_bike(request, pk):
    bike = get_object_or_404(Bike, pk=pk)
    bike.delete()
    return redirect("listar-bikes")





# Garantir que essa view retornar a lista de todos as bicicletas
def listar_bikes(request):

    bikes = Bike.objects.all() # -> Isso consulta no banco

    filtro =  request.GET.get('buscar') # pegar o filtro

    if filtro:
        bikes = bikes.filter(modelo__icontains=filtro) # Isso é uma consulta no banco de dados

    return render (request, 'produtos.html', {'bikes': bikes})


# def listar_lojas(request):
#     lojas = Loja.objects.all()
#     return render(request, 'lojas.html', {'lojas': lojas})


# def detalha_loja(request, id):
#     loja = get_object_or_404(Loja, pk=id)
#     return render(request, "detalhe_loja.html", {"loja": loja})


@login_required
def cadastrar_vendedor(request):

    if request.method == 'POST':
        vendedor_form = VendedorModelForm(request.POST)
        if vendedor_form.is_valid():
            vendedor_form.save()
            return redirect("lista-vendedores")
        

    vendedor_form = VendedorModelForm()
    return render(request, 'formulario_vendedor.html', {'form': vendedor_form})


def listar_vendedores(request):
    vendedores = Vendedor.objects.all()

    return render(request, 'vendedores.html', {'vendedores': vendedores})


def contact_view(request):
    if request.method == "POST":
        form = ContactFormSet(request.POST)
        if form.is_valid():
            # Processar os dados do formulário
            pass
    else:
        form = ContactFormSet()

    return render(request, "contact.html", {"form": form})

def atualizar_vendedor(request, pk):
    # Primeiro passo é pegar o vendedor
    vendedor = get_object_or_404(Vendedor, pk=pk)

    if request.method == 'POST':
        # No formulario passar os dados de POST e a instância do modelo
        form = VendedorModelForm(request.POST, instance=vendedor)
        if form.is_valid():
            form.save()
            return redirect("lista-vendedores")
    else:
        form = VendedorModelForm(instance=vendedor)
    return render(request, "formulario_atualizar_vendedor.html", {'form':form, "vendedor": vendedor})

bikes/templates/contact.html
<!-- contact.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Contact</title>
</head>
<body>
    <h1>Contact Us</h1>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Send</button>
    </form>
</body>
</html>

bikes/templates/detalhe_loja.html
{% extends "base/base.html" %}

{% load static %}
{% block head %}
     <link rel="stylesheet" href="{% static "bikes/css/container_produtos.css" %}">
{% endblock head %}
{% block conteudo %}

<h1> Sobre a loja </h1>
{% comment %} <a href='{% url "atualizar-loja" loja.id %}'>Atualizar</a> {% endcomment %}
<form method='GET' action='{% url "atualizar-loja" loja.id %}'>
    {% csrf_token %}
    <button type='submit'>Atualizar</button>
</form>
{% comment %} <a href='{% url "deletar-loja" loja.id %}'>Deletar</a> {% endcomment %}


<form method='DELETE' action='{% url "deletar-loja" loja.id %}'>
    {% csrf_token %}
    <button type='submit'>Deletar</button>
</form>

<h2> Nome: {{loja.nome}} </h2>
<p> CNPJ: {{loja.cnpj}}</p>

<h3> Lista de produtos da Loja </h3>
<div class='container-produtos'>
    {% for produto in loja.produtos.all %}
    
        <div class='produto-item'>
    
            <h2>{{produto.modelo}}</h2>
           
            <img class='foto' src='{{produto.foto.url}}'/>
            
            <p>{{produto.descricao}}</p>
            <h3>R$ {{produto.preco}}</h3>
            
        </div>
        {% endfor %}
</div>
<h3> Lista de vendedores da Loja </h3>

<div class='container-produtos'>
    {% for vendedor in loja.vendedores.all %}
    
        <div class='produto-item'>
            <h2>Vendedor: {{vendedor.nome}}</h2>
            <p>CPF: {{vendedor.cpf}}</h2>
            
        </div>
        {% endfor %}
</div> 
{% endblock conteudo %}

bikes/templates/form_snippet.html
<!-- form_snippet.html -->
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}

bikes/templates/formulario_atualizar_vendedor.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "bikes/css/form_produtos.css" %}">
{% endblock head %}



{% block conteudo %}
    <h2> Formulário de atualizar o vendedor {{vendedor.nome}}</h2>
    <form method='POST' action='{% url "atualiza-vendedor" vendedor.id%}'>
        {% csrf_token %}
        {{form.as_p}}

        <button type='submit'>Atualizar</button>

    </form>

{% endblock conteudo %}

bikes/templates/formulario_bike.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "bikes/css/form_produtos.css" %}">
{% endblock head %}



{% block conteudo %}

    <form method='POST' enctype='multipart/form-data' action='{% url "cadastra-bike" %}'>
        {% csrf_token %}
        {{form.as_p}}

        <button type='submit'>Cadastrar</button>

    </form>

{% endblock conteudo %}

bikes/templates/formulario_bike_update.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "bikes/css/form_produtos.css" %}">
{% endblock head %}



{% block conteudo %}
    <h2> Formulário de atualização de Bikes </h2>
    <form method='POST' enctype='multipart/form-data' action='{% url "atualiza-bike" bike.id %}'>
        {% csrf_token %}
        {{form.as_p}}

        <button type='submit'>Atualizar</button>

    </form>

{% endblock conteudo %}

bikes/templates/formulario_loja.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "bikes/css/form_produtos.css" %}">
{% endblock head %}



{% block conteudo %}
    <h2> Formulário de cadastro de loja </h2>
    <form method='POST' action='{% url "cadastra-loja" %}'>
        {% csrf_token %}
        {{form.as_p}}

        <button type='submit'>Cadastrar</button>

    </form>

{% endblock conteudo %}

bikes/templates/formulario_loja_update.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "bikes/css/form_produtos.css" %}">
{% endblock head %}



{% block conteudo %}
    <h2> Formulário de cadastro de loja </h2>
    <form method='POST' action='{% url "atualizar-loja" loja.id %}'>
        {% csrf_token %}
        {{form.as_p}}

        <button type='submit'>Atualizar</button>

    </form>

{% endblock conteudo %}

bikes/templates/formulario_vendedor.html
{% extends "base/base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "bikes/css/form_produtos.css" %}">
{% endblock head %}



{% block conteudo %}
    <h2> Formulário de cadastro de vendedor </h2>
    <form method='POST' action='{% url "cadastra-vendedor" %}'>
        {% csrf_token %}
        {{form.as_p}}

        <button type='submit'>Cadastrar</button>

    </form>

{% endblock conteudo %}

bikes/templates/home.html
{% extends "base/base.html" %} 
{% load static %} 
{% block conteudo %}
<div class="conteudo">
        <div class="introducao">
            <span class="detalhe"></span>
            <h1>Bicicletas Feita a Mão</h1>
            <p> A nimbus Stark é a melhor Bikcraft já criada pela nossa eqipe. Ela vem com os melhores acessórios da marca.</p>
            <a class="botao" href="/">Ver mais</a>
        </div>
        <img src="{% static "bikes/img/bicicleta.jpg" %}" alt="Bicicleta Bikcraft">

        <h2 class="subtitulo">Vantagens Bikcraft</h2>

        <div class="vantagens">
            <div class="vantagens-item">
                <img src="{% static "bikes/img/eletrica.svg" %}" alt="">
                <h3>Motor Elétrico</h3>
                <p>Permite você viajar distâncias inimagináveis com a sua bike</p>
            </div>
            <div class="vantagens-item">
                <img src="{% static "bikes/img/velocidade.svg" %}" alt="">
                <h3>40 Km/h</h3>
                <p>A mais rápida bicicltea elétrica disponível hoje no mercado</p>
            </div>
            <div class="vantagens-item">
                <img src="{% static "bikes/img/rastreador.svg" %}" alt="">
                <h3>Rastreador</h3>
                <p>Rastreador e sistema anti-furto para garantir o seu sossego.</p>
            </div>

        </div>

    </div>

{% endblock conteudo %}

bikes/templates/lojas.html
{% extends "base/base.html" %}
{% load static %}


    {% block head %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head>
    {% endblock head %}
<body>


    {% block conteudo %}
    
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1>Lista de Lojas</h1>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12">
                <input type="text" class="form-control" id="search" placeholder="Pesquisar lojas...">
            </div>
        </div>

        <a href='{% url "cadastra-loja" %}' class='btn btn-primary mt-3'>Cadastrar loja</a>
        <div class="row mt-4" id="store-list">
            {% for loja in lojas %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <a href='{% url "detalha-loja" loja.id%}'><div class="card-body">
                        <h5 class="card-title">{{loja.nome}}</h5>
                        <p class="card-text">{{loja.cnpj}}</p>
                        <p class="card-text">{{loja.detalhes}}</p>
                    </div></a>
                </div>
            </div>
            {% endfor %}
           
        </div>
    </div>
    
    {% endblock conteudo %}

    {% block script %}
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    {% endblock script %}

bikes/templates/produtos.html
{% extends "base/base.html" %}
{% load static %}
{% block head %}
     <link rel="stylesheet" href="{% static "bikes/css/container_produtos.css" %}">
{% endblock head %}


{% block conteudo %}
<div class='container-produtos'>
    <div class="row mt-4">
        <form method='GET' action='{% url "listar-bikes" %}'>
            <input type="text" name='buscar'  placeholder="Pesquisar produtos...">
        </form>
       
        
    </div>
    <a href='{% url "cadastra-bike" %}' class='btn btn-primary mt-3'>Cadastrar Produto</a>

    <div class="row">
           
    </div>
        {% if message %}
            <h1> {{message}} </h1>
        {% endif %}
        
        {% for bike in bikes %}
        <div class='produto-item'>

            
            <h2>{{bike.modelo}}</h2>
            
            <img class='foto' src='{{bike.foto.url}}'/>
            
            <p>{{bike.descricao}}</p>
            <h3>R$ {{bike.preco}}</h3>
            <ul>
                {% for loja in bike.loja_set.all %}
                <li> Loja: {{loja.nome}}</li>
                {% endfor %}
            </ul> 
            <a href='{% url "atualiza-bike" bike.id%}'>Atualizar</a><br>
            <a href='{% url "deleta-bike" bike.id%}'>Deletar</a>
            
        </div>
        {% endfor %}
        
</div>

{% endblock conteudo %}

bikes/templates/vendedores.html
{% extends "base/base.html" %}

{% load static %}

{% block head %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head>
{% endblock head %}



{% block conteudo %}

<div class="container mt-5">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Lista de Vendedores</h1>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <input type="text" class="form-control" id="search" placeholder="Pesquisar vendedor..">
        </div>
    </div>

    <a href='{% url "cadastra-vendedor" %}' class='btn btn-primary mt-3'>Cadastrar vendedor</a>
    <div class="row mt-4" id="store-list">
        {% for vendedor in vendedores %}
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">{{vendedor.nome}}</h5>
                    <p class="card-text">{{vendedor.cpf}}</p>
                    <p class="card-text">{{vendedor.loja}}</p> 
                    <a href='{% url "atualiza-vendedor" vendedor.id %}' class='btn btn-primary mt-3'>atualizar vendedor</a>

                </div>
            </div>
        </div>
        {% endfor %}
       
    </div>
</div>

{% endblock conteudo %}

    {% block script %}
    
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    {% endblock script %}
</body>
</html>